config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get "home/about" => "homes#about", as: 'about'
  get "search" => "searches#search"
  get 'tagsearches/search', to: 'tagsearches#search'
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource:favorites, only: [:index, :create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
    get "search" => "users#search"
    member do
      get :follows, :followers
    end
      resource :relationships, only: [:create, :destroy]
  end

  resources :messages, only: [:create]
  resources :rooms, only: [:create,:show]
  resources :groups, only: [:new, :index, :show, :create, :edit, :update] do
    resource :group_users, only: [:create, :destroy]
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :followers, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followeds, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_users, through: :followers, source: :followed
  has_many :follower_users, through: :followeds, source: :follower
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :read_counts, dependent: :destroy
  has_many :group_users, dependent: :destroy

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true

  validates :introduction, length: { maximum: 50 }

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
  #　フォローしたときの処理
  def follow(user_id)
    followers.create(followed_id: user_id)
  end

  #　フォローを外すときの処理
  def unfollow(user_id)
    followers.find_by(followed_id: user_id).destroy
  end

  #フォローしていればtrueを返す
  def following?(user)
    following_users.include?(user)
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  def guest_user?
    email == GUEST_USER_EMAIL
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: "guestuserでログインしました。"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update, :edit,]
  before_action :authenticate_user!, only: [:show]
  before_action :ensure_guest_user, only: [:edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @today_book = @books.created_today
    @yesterday_book = @books.created_yesterday
    @this_week_book = @books.created_this_week
    @last_week_book = @books.created_last_week
    @book = Book.new
    @following_users = @user.following_users
    @follower_users = @user.follower_users
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    if @user.id == current_user.id
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
    if params[:created_at] == "" #入力が空欄なら
      @search_book = "日付を選択してください"
    else
      create_at = params[:created_at]
      @search_book = @books.where(['created_at LIKE ? ', "#{create_at}%"]).count
    end
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    ensure_correct_user
    @user = User.find(params[:id])
  end

  def update
    ensure_correct_user
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      @users = User.all
      render :edit
    end
  end

  # フォロー一覧
  def follows
    user = User.find(params[:id])
    @users = user.following_users
  end

  # フォロワー一覧
  def followers
    user = User.find(params[:id])
    @user = user.follower_users
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.guest_user?
      redirect_to user_path(current_user) , notice: "ゲストユーザーはプロフィール編集画面へ遷移できません。"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '80x80' %></td>
        <td><%= user.name %></td>
        <td>フォロー<%= user.followers.count %></td>
        <td>フォロワー<%= user.followeds.count %></td>
        <td><% if current_user != user %>
              <% if current_user.following?(user) %>
                <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-danger" %>
              <% else %>
                <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class:"btn btn-success" %>
              <% end %>
            <% end %>
        </td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
	  <th>follows</th>
	    <th>
        <%= link_to follows_user_path(user) do %>
          <h6><%= user.followers.count %></h6>
        <% end %>
      </th>
  </tr>
  <tr>
	  <th>followers</th>
	    <th>
        <%= link_to followers_user_path(user) do %>
          <h6><%= user.followeds.count %></h6>
        <% end %>
      </th>
  </tr>
</table>
<table>
  <% unless user.guest_user? %>
    <div class='row'>
      <% if current_user != user %>
        <td><%= render "relationships/follow_btn", user: user %></td>
      <% else %>
        <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
          <i class="fas fa-user-cog"></i>
        <% end %>
      <% end %>
    </div>
  <% end %>
</table>

app/views/users/_search.html.erb
<h4>検索結果</h4>
<table class="table">
  <thead>
    <tr>
      <th>投稿数</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= search_book %></td>
    </tr>
  </tbody>
</table>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<h2>Follower Users</h2>
<table class='table'>
  <thead>
    <tr>
      <th>Image</th>
      <th>name</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @user.each do |user| %>
      <tr>
        <td>
          <%= link_to user_path(user) do %>
            <%= image_tag user.get_profile_image, size: '50x50' %>
          <% end %>
        </td>
        <td><%= user.name %></td>
        <td>
          <%= link_to follows_user_path(user) do %>
            <p>フォロー数:<%= user.followers.count %></p>
          <% end %>
        </td>
        <td>
          <%= link_to followers_user_path(user) do %>
            <p>フォロワー数:<%= user.followeds.count %></p>
          <% end %>
        </td>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/follows.html.erb
<h2>Follow Users</h2>
  <table class='table'>
    <thead>
      <tr>
        <th>Image</th>
        <th>name</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td>
            <%= link_to user_path(user) do %>
              <%= image_tag user.get_profile_image, size: '50x50' %>
            <% end %>
          </td>
          <td><%= user.name %></td>
          <td>
            <%= link_to follows_user_path(user) do %>
              <h6>フォロー数:<%= user.followers.count %></h6>
            <% end %>
          </td>
          <td>
            <%= link_to followers_user_path(user) do %>
              <h6>フォロワー数:<%= user.followeds.count %></h6>
            <% end %>
          </td>
          <td><%= link_to 'Show', user %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/users/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3"><h2>User info</h2>
      <%= render 'info', user: current_user %>

      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
        <%=link_to "グループを作成する",new_group_path %> |
        <%=link_to "グループ一覧",groups_path %>
        <%= render 'index', users: @users, user: current_user %>
    </div>
  </div>
</div>

app/views/users/search.js.erb
$('#search_result').html("<%= j(render 'search', search_book: @search_book ) %>");

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <% unless @user.id == current_user.id %>
        <% if (current_user.following? @user) && (@user.following? current_user)  %>
        <% if @isRoom == true %>
          <p class="user-show-room"><a href="/rooms/<%= @roomId %>" class="btn btn-primary btn-lg">チャットへ</a>
        <% else %>
          <%= form_with model: @room do |f| %>
            <%= fields_for @entry do |e| %>
              <%= e.hidden_field :user_id, value: @user.id %>
            <% end %>
            <%= f.submit "チャットを始める", class:"btn btn-primary btn-lg user-show-chat"%>
          <% end %>
        <% end %>
        <% end %>
      <% end %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
      <h2>7日分の投稿数</h2>
      <table class="table table-bordered ">
        <tr>
          <th>今日</th>
          <th>1日前</th>
          <th>2日前</th>
          <th>3日前</th>
          <th>4日前</th>
          <th>5日前</th>
          <th>6日前</th>
        </tr>
        <tr>
          <td><%= @books.created_today.count %></td>
          <td><%= @books.created_yesterday.count %></td>
          <td><%= @books.created_2day_ago.count %></td>
          <td><%= @books.created_3day_ago.count %></td>
          <td><%= @books.created_4day_ago.count %></td>
          <td><%= @books.created_5day_ago.count %></td>
          <td><%= @books.created_6day_ago.count %></td>
        </tr>
      </table>
      <canvas id="myLineChart"></canvas>
      <script>
        $(document).on('turbolinks:load', function() {
          var ctx = document.getElementById("myLineChart");
          var myLineChart = new Chart(ctx, {
            type: 'line',
            data: {
              labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],
              datasets: [
                {
                  label: '投稿した本の数',
                  data: [
                    <%= @books.created_6day_ago.count %>,
                    <%= @books.created_5day_ago.count %>,
                    <%= @books.created_4day_ago.count %>,
                    <%= @books.created_3day_ago.count %>,
                    <%= @books.created_2day_ago.count %>,
                    <%= @books.created_yesterday.count %>,
                    <%= @books.created_today.count %>
                  ],
                  borderColor: "rgba(0,0,255,1)",
                  backgroundColor: "rgba(0,0,0,0)",
                  tension: 0.4
                }
              ],
            },
            options: {
              title: {
                display: true,
                text: '7日間の投稿数の比較'
              },
              responsive: true,
              scales: {
                y:{
                  suggestedMin: 0,
                  suggestedMax: 10
                },
                x:{
                  stacked: true
                },
              },
            }
          });
        });
      </script>
      <%= form_with url: user_search_path(@user), method: :get, local: false do |f| %>
        <%= f.date_field :created_at %>
        <%= f.submit '検索', class: "btn btn-primary" %>
      <% end %>

      <div id="search_result">
        <% if @search_book.present? %>
          <%= render 'search', search_book: @search_book %>
        <% end %>
      </div>
    </div>
  </div>
</div>